### ISSUE TITLE
Fog persists between map TPs

### ISSUE THREAD

**Issue by DalekCraft2** [surrealegg/debug-console#6]
I was in Pinwheel Forest and teleported to Breaven, and the fog persisted. It only disappeared once I went back to Pinwheel Forest and then left.

The inverse is also true, where teleporting from a fogless map to a map with fog will result in no fog until the player transitions into a room which uses a different fog setting.

**Comment by surrealegg** [comment]
Solved at https://github.com/surrealegg/debug-console/commit/63dfcf04f9a5f79605094c18bca1226b2043a1e6
